[package]
name = "datahotel"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version= "4.5.38", features = ["derive"]}
rand = "0.9.2"

[dependencies.rusqlite]
version = "0.38.0"
features = ["bundled-sqlcipher-vendored-openssl"]
